============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
Creating Data
Using default paths: data_path=data/steam/total_data.hdf5, index_path=data/steam/index.npz
Loading data from data/steam/total_data.hdf5
Loaded raw data with shape: (31075, 3)
Loading index from data/steam/index.npz
Loaded index with shape: (31075,)
Remapping user and item IDs
Identifying valid users and items
Scanning for valid entries:   0%|          | 0/31075 [00:00<?, ?it/s]Scanning for valid entries: 100%|██████████| 31075/31075 [00:00<00:00, 909121.32it/s]
Found 1100 valid users and 2431 valid items
User and item mapping created
Creating new data and index arrays with mapped IDs
Remapping data:   0%|          | 0/31075 [00:00<?, ?it/s]Remapping data: 100%|██████████| 31075/31075 [00:00<00:00, 869656.29it/s]
Remapped data shape: (5545, 3), index shape: (5545,)
Loading item data
Using default item_path: data/steam/steam.item
Reading item data from data/steam/steam.item
Loaded item data with shape: (5, 13)
Traceback (most recent call last):
  File "/home/scur2748/.conda/envs/inf-ae/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'genre:token_seq'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home5/scur2748/inf-ae/main.py", line 118, in <module>
    main(hyper_params)
  File "/gpfs/home5/scur2748/inf-ae/main.py", line 108, in main
    data = Dataset(hyper_params)
  File "/gpfs/home5/scur2748/inf-ae/data.py", line 16, in __init__
    self.data = load_raw_dataset(
  File "/gpfs/home5/scur2748/inf-ae/data.py", line 151, in load_raw_dataset
    for genre_list in item_df[category_id].fillna("[Nan]")
  File "/home/scur2748/.conda/envs/inf-ae/lib/python3.9/site-packages/pandas/core/frame.py", line 4107, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/scur2748/.conda/envs/inf-ae/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 'genre:token_seq'

JOB STATISTICS
==============
Job ID: 12292615
Cluster: snellius
User/Group: scur2748/scur2748
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:05
CPU Efficiency: 2.40% of 00:03:28 core-walltime
Job Wall-clock time: 00:00:13
Memory Utilized: 1.49 MB
Memory Efficiency: 0.00% of 180.00 GB (180.00 GB/node)
